server.port: 9000

solon:
  app:
    group: network-proxy
    name: network-proxy-client
  config:
    add: ./app.yml

solon.logging.appender:
  console:
    level: INFO
  file:
    level: INFO
    name: "logs/${solon.app.name}"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd}/%i.log"
    maxFileSize: "10 MB"
    maxHistory: "7"

solon.logging.logger:
  "root": #默认记录器配置
    level: INFO
  "io.netty":
    level: WARN

tunnel.serverUrl: "sd:tcp://127.0.0.1:8602"
tunnel.clientId: "115066186"
